### ISSUE TITLE
Question: works in dev mode?

### ISSUE THREAD

**Issue by cherihung** [jaredLunde/snowpack-plugin-svgr#3]
Really neat plugin! Trying it out and I see it works perfectly when I build the project for production (`snowpack build`) but in the dev mode (`snowpack dev`), it doesn't seem to work.
I'd get a 404 not found when the app is looking for the generated react component file for an svg.

for example,
```
import Logo from './logo.svg';

 <Logo />
```

In dev mode, I get the following error:
`http://localhost:8080/_dist_/logo.js net::ERR_ABORTED 404 (Not Found)`

Is this as expected as of now?

Looking into this, it seems the plugin needs to generate a proxy response for dev mode.
possibly related: https://github.com/snowpackjs/snowpack/issues/542#issuecomment-650699207
but I'm not entirely sure how to suggest a solution right now. need to checkout the snowpack plugin interface some more.
thought I'd pose the question in case this is in the works.

**Comment by sntg-p** [comment]
I'm having the same problem.

**Comment by Relaxe111** [comment]
[Here](https://github.com/Relaxe111/snowpack-react-ts-scss_modules-svg_as_react_components-antd) where it works with svg as react components.
To make it work remove from package.json react-doc-viewer and from App.tsx imported component from that package.
After as usual yarn install & yarn start. Please let me know if is not working for you.

**Comment by cherihung** [comment]
@Relaxe111 thanks! yep the example worked for me.  And after I updated my project to use the latest snowpack version and added the plugin back to the config, the plugin worked great in both dev and prod mode now.

My issue might have been fixed with the latest snowpack (?)

👍  thanks for checking it out.

**Comment by Relaxe111** [comment]
It might be so) I am glad it was useful )

**Comment by jaredLunde** [comment]
Thanks @Relaxe111
